/**
* @fileoverview This file is generated by the Angular template compiler.
* Do not edit.
* @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
* tslint:disable
*/ 
var styles = [".box-css[_ngcontent-%COMP%] {\r\n    margin-top: 40px;\r\n}"];
export { styles as styles };
