/**
* @fileoverview This file is generated by the Angular template compiler.
* Do not edit.
* @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
* tslint:disable
*/ 
var styles = [".config[_ngcontent-%COMP%] {\r\n    display: inline-block;\r\n    text-align: right;\r\n    width: 19%;\r\n}\r\n\r\n.author[_ngcontent-%COMP%] {\r\n    display:inline-block;\r\n    width: 80%;\r\n    font-style: italic;\r\n}"];
export { styles as styles };
